spring:
  thymeleaf:
    cache: false
  datasource:
    username: order
    password: 123456
    url: jdbc:mysql://localhost:3306/order_system?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080